---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(hrbrthemes)
```

## Ingest data

```{r message=FALSE, warning=FALSE}
pre <- read_csv("data/20210204_pre_viz-flipped_part2.csv") %>%
  mutate("survey" = "pre")
post <- read_csv("data/20210204_pre_viz-flipped_part2.csv") %>% 
  mutate("survey" = "post")
```

## Wrangle data

Normalize column labels

```{r}
new_names_pre <- c("timestamp", "tools_coder", "tools_viz", 
                   "tools_version_ctrl", "tools_cli", "tools_rdbms",
                   "import_experience", "scripts_experience", 
                   "baser_viz_experience", "ggplot2_experience",
                   "interactive_experience", 
                   "pivot_experience", "join_experience",
                   "data_mgt_satisfy", "survey")
new_names_post <- c("timestamp", "tools_coder", "tools_models", 
                   "tools_rdbms", "tools_version_ctrl", "tools_cli", 
                   "import_experience", "scripts_experience", 
                   "subset_experience",
                   "projects_experience", 
                   "reproducible_experience", "self_help",
                   "search_help", "apply_learning",
                   "what_worked_qual", "curric_continue_qual", 
                   "curric_expand_qual", "survey")


colnames(pre) <- new_names_pre
colnames(post) <- new_names_post

# colnames(pre)
# colnames(post)
```

make one table

```{r}
# post <-  pre

# post <- post %>% mutate(survey = "post")

pre_post_tbl <- bind_rows(pre, post)
```

## Visualize

```{r big picture, fig.height=15, fig.width=20, message=FALSE, warning=FALSE}
pre_post_tbl %>% 
  select(timestamp, survey, ends_with("_experience")) %>% 
  pivot_longer(ends_with("_experience"),
               names_to = "experience") %>% 
  filter(experience != "import_experience" & experience != "scripts_experience") %>% ################################
  mutate(value = str_to_title(value)) %>% 
  mutate(value = fct_relevel(value, levels = c("Strongly Disagree",
                                       "Disagree",
                                       "Neutral", "Agree", 
                                       "Strongly Agree"))) %>% 
  mutate(experience = str_extract(experience, "\\w+(?=_)")) %>% 
  mutate(experience = fct_relevel(experience, levels = c(
    "import", "subset", "scripts", "projects", "reproducible")
  )) %>% 
  ggplot(aes(value)) +
    geom_bar(aes(fill = value), color = "black") +
    facet_grid(experience ~ fct_rev(str_to_title(survey)))+ 
    scale_fill_brewer(palette = "BrBG") + 
    scale_y_continuous(breaks = c(0,2,4,6)) +
    scale_x_discrete(labels = scales::label_wrap(10)) +
    hrbrthemes::theme_ipsum(grid = "Y", ticks = TRUE) +
    theme(legend.position="none", plot.title.position = "plot") +
  labs(title = "Comparison of Pre & Post survey results",
       x = "", y = "",
       caption = "Source: Registrant surveys at time of workshop")

ggsave("output/images/big_picture.svg", width = 15, height = 10, units = "in")
# ggsave("C:/Users/jrl/Documents/workshop_rfun_flipped/slides/images/pre_post_survey2_20210204.svg",
#        width = 15, height = 10, units = "in")
```


```{r warning=FALSE}
pre_post_tbl %>% 
  filter(survey == "pre") %>% 
  select(timestamp, survey, ends_with("_experience")) %>% 
  pivot_longer(ends_with("_experience"),
               names_to = "experience") %>% 
  mutate(value = str_to_title(value)) %>% 
  mutate(value = fct_relevel(value, levels = c("Strongly Disagree",
                                       "Disagree",
                                       "Neutral", "Agree", 
                                       "Strongly Agree"))) %>% 
  mutate(experience = str_extract(experience, "\\w+(?=_)")) %>% 
  ggplot(aes(value)) +
    geom_bar(aes(fill = value), color = "black") +
    scale_fill_brewer(palette = "BrBG") + 
    hrbrthemes::theme_ipsum(grid = "Y", ticks = TRUE) +
    theme(legend.position="none", plot.title.position = "plot") +
  labs(title = "Conflated Experience of Pre survey results",
       x = "", y = "",
       caption = "Source: Registrant surveys at time of workshop")
```

```{r fig.width=12}
pre_post_tbl %>% 
  # filter(survey == "post") %>% 
  select(timestamp, survey, ends_with("_experience")) %>% 
  pivot_longer(ends_with("_experience"),
               names_to = "experience") %>% 
  mutate(value = str_to_title(value)) %>% 
  mutate(value = fct_relevel(value, levels = c("Strongly Disagree",
                                       "Disagree",
                                       "Neutral", "Agree", 
                                       "Strongly Agree"))) %>% 
  mutate(experience = str_extract(experience, "\\w+(?=_)")) %>% 
  ggplot(aes(value)) +
    geom_bar(aes(fill = value), color = "black") +
    scale_fill_brewer(palette = "BrBG") + 
    facet_wrap(~ fct_rev(str_to_title(survey))) +
    hrbrthemes::theme_ipsum(grid = "Y", ticks = TRUE) +
    theme(legend.position="none", plot.title.position = "plot") +
  labs(title = "Conflated experience of survey results",
       subtitle = "Across all categories",
       x = "", y = "",
       caption = "Source: Registrant surveys at time of workshop")
```

